---
title: "About"
---

I am fascinated by planetary atmospheres.
In my research, I try to unravel the complexity of atmospheric processes on terrestrial planets using an hierarchy of 3D climate models.
I am particularly interested in the role of convection and clouds in the planetary habitability.
I am a member of the [Exoclimatology Theory Group (ETG)](https://www.exoclimatology.com/), where we use an hierarchy of numerical models (such as the Met Office Unified Model and [LFRic](research/lfric.qmd)) to study the diverse zoo of planetary climates.

Since 2025, I am a Lecturer in the Astrophysics group at the University of Bristol.
Before that, I was a postdoctoral research fellow at the Department of Physics and Astronomy, University of Exeter where I worked with [Nathan Mayne](https://experts.exeter.ac.uk/380-nathan-mayne) and [Hugo Lambert](https://experts.exeter.ac.uk/4403-hugo-lambert) on simulating atmospheres of terrestrial exoplanets.
I got a PhD at the University of East Anglia under the supervision of [Ian Renfrew](https://research-portal.uea.ac.uk/en/persons/ian-renfrew) and [Thomas Spengler](https://www4.uib.no/en/find-employees/Thomas.Spengler) (University of Bergen).
My PhD research was focused on the meteorology of high-latitude mesoscale cyclones, known as polar lows, and how their occurrence and evolution are affected by orography and sea ice in the Arctic.
I got my MSc-equivalent degree - Specialist Diploma in Meteorology and Climatology - at the Moscow State University.

{{< video https://www.youtube.com/embed/_Aus842EZWk >}}